fix(wallet): adds utxo selection to manual spend on wallet interface
unchained-capital/caravan pull request #223
Opened 2021-06-08 19:24 UTC by humanumbrella

## Description

Allow UTXO selection on manual spend in Wallet interface.

## Does this PR introduce a breaking change?

* [ ] Yes
* [X] No

## Does this PR fix an open issue?

* [X] Yes
* [ ] No

Fixes #54 

Follow-up to https://github.com/unchained-capital/caravan/pull/221 - adds in the necessary logic to handle utxo selection across multiple addresses

2021-06-09 16:57 UTC, bucko13 commented
Not sure how we want to handle since this isn't really blocking, but I found a small bug. 

To reproduce: 
1. author a transaction. in my example I have one that's a partial spend from address and a full spend
2. Go to send 
3. Go back to edit
4. Notice the select boxes for the address are no longer selected

What could be blocking though is that I selected only 1/2 of the UTXOs from an address however when going back it looks like both are selected. If this is the case and can be confirmed, I'd say this is blocking since we don't want someone accidentally spending all the UTXOs when they only meant to spend part. 

![Screen Shot 2021-06-09 at 11 53 53 AM](https://user-images.githubusercontent.com/4344978/121396987-8a80e300-c919-11eb-8098-d23ebb7d1f28.png)

2021-06-09 17:01 UTC, bucko13 requested changes
Couple of small comments on the code as is, but I think we should address the issue when you go back to edit after clicking to sign

2021-06-09 18:49 UTC, waldenraines commented
> Not sure how we want to handle since this isn't really blocking, but I found a small bug.
> 
> To reproduce:
> 
> 1. author a transaction. in my example I have one that's a partial spend from address and a full spend
> 2. Go to send
> 3. Go back to edit
> 4. Notice the select boxes for the address are no longer selected
> 
> What could be blocking though is that I selected only 1/2 of the UTXOs from an address however when going back it looks like both are selected. If this is the case and can be confirmed, I'd say this is blocking since we don't want someone accidentally spending all the UTXOs when they only meant to spend part.

This is also the case if you navigate away from the spend tab (by going to the addresses or receive tab, for example).  When you come back you end up in the same state as shown in the screenshot.

2021-07-08 12:25 UTC, humanumbrella commented on package.json
> +    "unchained-wallets": "^0.1.21"
Yes - just bumping it to the latest.

2021-07-08 12:25 UTC, humanumbrella commented on src/components/ScriptExplorer/UTXOSet.jsx
> +  componentDidUpdate(prevProps, prevState, snapshot) {
We don't - editor complains if those are missing, linter complains if they're there and unused. Removing

2021-07-08 12:28 UTC, humanumbrella commented
I updated things to make sure that it at least shows that the address is now **selected** (full checkbox, not indeterminate or missing) when you navigate away and/or click edit transaction.

It will require more effort given the current design to actually save which inputs were selected. It would be easier with a larger refactor of how the application is structured.

2021-07-27 01:04 UTC, bucko13 commented
Don't know if this needs to be a blocker, but this was a weird little bug. If there's only one UTXO in an address, selecting it in the utxo selector doesn't work: 

https://user-images.githubusercontent.com/4344978/127078598-f1b7d0e5-9b92-4d59-afef-47ddbfb67fda.mp4

2021-07-27 01:07 UTC, bucko13 commented
Tested happy path and the reset of the utxos if going back to edit and it all seems to work other than the bug identified above. If that is easily fixable, then it'd be good if we can get that in (maybe just disabling that view if only one utxo as a quick fix? 🤷‍♂️ ). Otherwise it LGTM!

2021-07-27 23:08 UTC, bucko13 approved these changes
Confirmed it works! 👏 🎉 :shipit:

2021-07-28 19:24 UTC, merged