Update README.md
unchained-capital/caravan pull request #247
Opened 2021-12-30 15:58 UTC by bucko13

## Description
include links to node/npm installation instructions for those who don't already have them installed. 

## Does this PR introduce a breaking change?

* [ ] Yes
* [x] No

## Does this PR fix an open issue?

* [ ] Yes
* [x] No

2022-01-02 19:02 UTC, waldenraines commented
```
> commitlint-travis
⧗   input: Update README.md
include links to node/npm installation instructions.
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]
✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```

2022-01-05 00:42 UTC, humanumbrella approved these changes

2022-03-02 04:51 UTC, humanumbrella requested changes

2022-03-02 04:51 UTC, humanumbrella commented on README.md
> +node and npm bsed on your platform [here](https://nodejs.org/en/download/) or
`bsed` => `based`

2022-03-02 04:52 UTC, humanumbrella commented on README.md
> +node and npm bsed on your platform [here](https://nodejs.org/en/download/) or
also commitlint isn't happy with `Update README`

2023-03-30 22:59 UTC, closed without merging