Hermit PSBT signing for pre-product key recovery
unchained-capital/caravan pull request #308
Opened 2023-05-27 05:24 UTC by humanumbrella

## Description

This PR simply attempts to bring an existing feature branch into the mainline -- it is working in the feature branch, but we don't want to leave the code dangling there indefinitely. This functionality is used for pre-product key recovery signing via hermit and is, therefore, a bit challenging to test. I have a write up somewhere, but want to get this branch up to date with `master` and more or less ready to go. My goal is to put this code in to `master` ... and have it be the first attempt next time it's needed.

## Does this PR introduce a breaking change?

* [x] Yes
* [ ] No

It removes pubkey exporting from hermit, which is no longer supported.

## Does this PR fix an open issue?

* [ ] Yes
* [x] No

2023-07-13 15:25 UTC, bucko13 reviewed
Mostly comments about cleanup.

2023-07-13 15:25 UTC, bucko13 commented on src/actions/transactionActions.js
> +    // FIXME make sure all redeem scripts are the same -- can only support this kind of spend
Cleanup? TODO? Log as an issue?

2023-07-13 15:25 UTC, bucko13 commented on src/actions/transactionActions.js
> +    // now do sigs
What does this comment mean? Can we remove it now?

2023-07-13 15:25 UTC, bucko13 commented on src/components/Hermit/HermitSignatureImporter.jsx
> +    //
nit cleanup

2023-07-13 15:25 UTC, bucko13 commented on src/components/ScriptExplorer/ScriptEntry.jsx
> +          // });
can this be cleaned up?

2023-07-13 15:25 UTC, bucko13 commented on src/reducers/transactionReducer.js
> +      return updateState(state, { unsignedPSBT: action.value });
future TODO but I suspect this probably didn't need to be in the redux store at all. Probably something we need to start moving away from eventually in Caravan.

2023-07-25 15:44 UTC, bucko13 requested changes
One tiny request on a leftover comment that needs some more clarification otherwise I think this is good enough to merge. 

It would be nice to refactor some of this in the future, simplifying the actions or removing them altogether as necessary. After some of our work on PSBTv2 in unchained-bitcoin I think there's particularly room to improve the API of managing the PSBT state at the application layer. to make these components a little easier to manage/maintain and understand what's going on. 

All for future work though!

2023-08-03 03:21 UTC, humanumbrella commented on src/actions/transactionActions.js
> +    // now do sigs
i thought i deleted that comment - if we want to support loading a **partially signed** PSBT ... we need to pay attention to included signatures in the psbt. i chose not to support that initially. will remove this comment.

2023-10-17 19:55 UTC, bucko13 approved these changes

2023-10-21 00:22 UTC, merged